# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0003_auto_20170319_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='years',
            field=models.IntegerField(default=18, verbose_name='\u5e74\u9f84'),
        ),
    ]
