# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170405_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tag',
            field=models.CharField(default='', max_length=15, verbose_name='\u8bfe\u7a0b\u6807\u7b7e'),
        ),
    ]
