# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgnization', '0003_auto_20170319_1644'),
        ('courses', '0006_video_learn_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgnization.Teacher', verbose_name='\u8bb2\u5e08'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher_tell',
            field=models.CharField(default='', max_length=300, verbose_name='\u8001\u5e08\u544a\u8bc9'),
        ),
        migrations.AddField(
            model_name='courses',
            name='youneed_know',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
    ]
