# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 10:05
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courses_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourses',
            fields=[
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u8bfe\u7a0b',
                'proxy': True,
                'verbose_name_plural': '\u8f6e\u64ad\u8bfe\u7a0b',
            },
            bases=('courses.courses',),
        ),
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.CharField(default='\u540e\u7aef\u5f00\u53d1', max_length=50, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u8bfe\u7a0b\u8be6\u60c5'),
        ),
    ]
